### ISSUE TITLE
confd reports error when watch etcd

### ISSUE THREAD

**Issue by randmonkey** [projectcalico/confd#32]
We are using a k8s cluster with calico network, and we found the following exception when adding a new machine into cluster.

One of the old machine failed to add the new machine into its BGP peers. Then, we checked logs of pod calico-node, and found the following logs 
```
2017-08-14 04:19:18.216 [INFO][124] int_dataplane.go 485: Received *proto.HostMetadataUpdate update from calculation graph msg=hostname:"cs58" ipv4_addr:"10.200.20.69"
2017-08-14 04:19:18.216 [INFO][124] int_dataplane.go 591: Applying dataplane updates
2017-08-14 04:19:18.216 [INFO][124] ipip_mgr.go 214: All-hosts IP set out-of sync, refreshing it.
2017-08-14 04:19:18.216 [INFO][124] ipsets.go 116: Queueing IP set for creation family="inet" setID="all-hosts" setType="hash:ip"
2017-08-14 04:19:18.217 [INFO][124] ipsets.go 685: Doing full IP set rewrite family="inet" numMembersInPendingReplace=3 setID="all-hosts"
2017-08-14 04:19:18.218 [INFO][124] int_dataplane.go 606: Finished applying updates to dataplane. msecToApply=1.4266420000000002
2017-08-14T04:19:18Z cs23 confd[122]: ERROR 401: The event in requested index is outdated and cleared (the requested history has been cleared [52945/210]) [53944]

bird: BGP: Unexpected connect from unknown address 10.200.20.69 (port 51526)
```
 We can see that node 10.200.20.69 has been already added into cluster in etcd, but confd failed to update BGP peer info into configuration of bird.

Then, we can see a lot of logs of confd like this:
```
2017-08-14T04:19:18Z cs23 confd[122]: ERROR 401: The event in requested index is outdated and cleared (the requested history has been cleared [52945/210]) [53944]
```
We searched for that and found that this error is generated by etcd client.
But we found that the error has been fixed in this PR of confd https://github.com/kelseyhightower/confd/pull/254, and this PR is already contained in the current version v0.12.1. So, why did this happen?
Note:
version of calico-node container: calico/node:v1.3.0
Versions of binaries:
calico-felix: v2.3.0
confd: v0.12.1-calico-0.1.0
bird: BIRD version 1.6.3
etcd: etcd-amd64:3.0.17
Note2: We restarted the calico-node pod, then it added the new BGP peer.

**Comment by heschlie** [comment]
This is odd, we do have the fix from that PR, but we've also made some changes to the etcd backend.  I'll see if I can repro using the steps from that from that PR and get a fix up.

**Comment by robbrockbank** [comment]
OK, so I believe we are inadvertently reintroducing this issue with the following change from the upstream etcdv2 Watcher:

```
func (c *Client) WatchPrefix(prefix string, keys []string, waitIndex uint64, stopChan chan bool) (uint64, error) {
	if waitIndex == 0 {
		resp, err := c.client.Get(context.Background(), prefix, &client.GetOptions{Quorum: true})
		if err != nil {
			return 0, err
		}
		return resp.Index, nil
	}
```

Compared to the upstream:
```
func (c *Client) WatchPrefix(prefix string, keys []string, waitIndex uint64, stopChan chan bool) (uint64, error) {
	// return something > 0 to trigger a key retrieval from the store
	if waitIndex == 0 {
		return 1, nil
	}
```

The problem with the upstream is that it has been changed to completely ignore the waitIndex and instead always watches from the current revision.  However, by ignoring the index of the last event we may miss events.  Consider the following flow (which is what confd does):
```
-  Watch current index
-  Event happens
-  Generate new templates
      <---- New event happens here
-  Watch current index
-  ...
```

In this example we miss the new event which happens while updating the templates.  Whilst this may be a small window, we were hitting it and our STs were failing intermittently as a result.

I think  we need to keep the changes that I made to ensure we use the revision (i.e. so we don't miss updates) and all the while the 401 is being hit, we effectively turn this into a polling loop - so we pause for a bit and do an update.

So after a little digging, I think this is what the code is already doing.  We catch the 401 and return a 0 index with a nil error - this should trigger the templates to be updated and then re-enter the watch loop.  

Since we aren't hitting this, I'm wondering if the client.Error check is actually working.  I believe that within this timeframe the etcdv2 client that we are using has been re-written.  It's odd that this check has remained the same though - so I suspect the code that checks the error is actually bugged.

So, next steps:
-  Investigate whether the error is being checked correctly.
-  Fix it if it isn't.
-  Do one of the following, so that we don't tight loop in this error case:
  -  If we hit 401, perform a Watch on the current index but with a short (5s?) timeout.  This effectively acts as a poll, but will exit earlier if an event occurs.
  -  or, more simply - just add a pause if we hit the error (again, 5s should be good).
-  Upstream the fix if possible.

**Comment by robbrockbank** [comment]
@heschlie see comments above - this would be a good one to take.

**Comment by ldnvnbl** [comment]
@robbrockbank You are right. I find the code from `coreos/etcd/client/keys.go`:

```
func unmarshalFailedKeysResponse(body []byte) error {
	var etcdErr Error
	if err := json.Unmarshal(body, &etcdErr); err != nil {
		return ErrInvalidJSON
	}
	return etcdErr
}
```

it return Error rather than the ptr *Error

**Comment by ldnvnbl** [comment]
@robbrockbank @heschlie Please review my fix pr and give me some comments, thanks.
